### ISSUE TITLE
Open permissions of repo

### ISSUE THREAD

**Issue by spenserw** [FasterMelee/FasterMelee-installer#21]
Would love to be able to slap PR's on this repo if people have discovered/resolved issues themselves. Tried this morning and wasn't able to due to permissions, @Ptomerty would you mind opening the repo up a bit more?

**Comment by Ptomerty** [comment]
Hey! I'm not quite sure how to open the permissions more than I already have, and people (well, one person) has submitted a PR in the past. Any idea how to do so?

**Comment by Ptomerty** [comment]
I just tried it myself and it seemed to work. Maybe you need to compare across forks instead?

https://github.com/Ptomerty/FasterMelee-installer/pull/22

**Comment by spenserw** [comment]
Sorry, must have been on my end. Apologies.
