### ISSUE TITLE
Thread question should use variable interpolation

### ISSUE THREAD

**Issue by ghost** [FasterMelee/FasterMelee-installer#23]
Change the single quotes on line 102 to double quotes.

    How many threads would you like to use to compile? (... max: $((CPUS + 1)))

to

    How many threads would you like to use to compile? (... max: 5)

**Comment by Ptomerty** [comment]
My bad, went too crazy trying to fix the missing quote earlier. Fixed here: https://github.com/Ptomerty/FasterMelee-installer/commit/58c50d8f4fe4ff8c0c61a3a549dec20ddb02c9c4
