### ISSUE TITLE
New installer no longer creates shortcut/link

### ISSUE THREAD

**Issue by StianOby** [FasterMelee/FasterMelee-installer#25]
The current installer doesn't create a shortcut/link when building any longer. I therefore have to dig up the "dolphin-emu" binary a couple of folders down.

(Not a particularly big issue, but it was convenient to have a link created automatically.)

**Comment by Ptomerty** [comment]
Hey: this was caused due to the installer failing right before the shortcut was created, due to a bad delete command, and has been fixed in the latest commit: https://github.com/Ptomerty/FasterMelee-installer/commit/7d1648c07ebdc60edf34abcd39ad7fe5ede9a17b

Thanks for informing me!
