### ISSUE TITLE
Oneliner

### ISSUE THREAD

**Issue by ErlingWis** [FasterMelee/FasterMelee-installer#28]
The "To use" code in README can be simplified to:
`sh -c "$(wget -q https://github.com/Ptomerty/FasterMelee-installer/raw/master/setup -O -)"`

**Comment by ErlingWis** [comment]
In README.MD ^

**Comment by Ptomerty** [comment]
What does the `-O -` at the end of wget do? never seen that before

**Comment by ErlingWis** [comment]
Sorry for the late response. The `-O` option lets you specify the output file. the `-` at the end specifies to write to stdout in stead of a file. 

[This works because the content of the url is plain text](https://raw.githubusercontent.com/Ptomerty/FasterMelee-installer/master/setup)

**Comment by ErlingWis** [comment]
`sh -c "$(wget -qO - https://github.com/Ptomerty/FasterMelee-installer/raw/master/setup)"` 
to save even more space 💃

**Comment by Ptomerty** [comment]
That's very interesting!

One last thing before I add this; is this as bad as piping into bash? Or
does wget complete fully before shell executes?

**Comment by ErlingWis** [comment]
If you remove the quiet option, you can see the wget output before the script starts:
```
 sh -c "$(wget -O - https://github.com/Ptomerty/FasterMelee-installer/raw/master/setup)"
--2017-08-05 23:28:39--  https://github.com/Ptomerty/FasterMelee-installer/raw/master/setup
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Ptomerty/FasterMelee-installer/master/setup [following]
--2017-08-05 23:28:40--  https://raw.githubusercontent.com/Ptomerty/FasterMelee-installer/master/setup
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.84.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.84.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5106 (5,0K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[================>]   4,99K  --.-KB/s    in 0s      

2017-08-05 23:28:40 (79,1 MB/s) - written to stdout [5106/5106]

tail -f  to follow along with the log for troubleshooting!

Attempting to delete incomplete installations of FM...

Would you like to overwrite ALL of your previous installations? (y/N)


```
So i would _assume_ the wget finishes before the shell is executed. I haven't done more testing than that.

**Comment by Ptomerty** [comment]
Good enough for me. Added here: https://github.com/Ptomerty/FasterMelee-installer/commit/8d5d003886b541b3d002f2b9cded6243bf24d4d9
