### ISSUE TITLE
libusb linking error

### ISSUE THREAD

**Issue by thegrb93** [FasterMelee/FasterMelee-installer#31]
```
../../../Externals/libusb/libusb.so.1.0.19: undefined reference to `linux_netlink_start_event_monitor'
../../../Externals/libusb/libusb.so.1.0.19: undefined reference to `linux_netlink_stop_event_monitor'
../../../Externals/libusb/libusb.so.1.0.19: undefined reference to `linux_netlink_hotplug_poll'
collect2: error: ld returned 1 exit status
make[2]: *** [Binaries/dolphin-emu] Error 1
make[1]: *** [Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/all] Error 2
make: *** [all] Error 2
```

Any ideas to fix this?

I'm running Linux Mint 18.2 Cinnamon 64-bit

**Comment by Ptomerty** [comment]
You need to have the dev version installed, not just libusb. Find out what
it's called in your package manager.

While you're at it, install dev packages for all the other dependencies as
well.

**Comment by thegrb93** [comment]
I did install everything mentioned in the README.md. Perhaps I need to use my system's libusb rather than the 'Externals' version?

**Comment by thegrb93** [comment]
Ah, so installing my distro's libusb should make it use that one. I'll see if I can find it.

**Comment by thegrb93** [comment]
I installed libusb-dev, however it's still using the 'Externals' one

**Comment by thegrb93** [comment]
Found it, it's libusb-1.0-0-dev

**Comment by thegrb93** [comment]
Thanks.

**Comment by Ptomerty** [comment]
No problem! Glad to hear you solved it.
