### ISSUE TITLE
Support updated glibc

### ISSUE THREAD

**Issue by rosshadden** [FasterMelee/FasterMelee-installer#32]
Can you please implement [this PR](https://github.com/dolphin-emu/dolphin/pull/5974)?  It lets dolphin compile with a newer glibc, which no longer has `xlocale.h`.

**Comment by rawsp33d** [comment]
I made the changes manually and successfully built, but it was actually a lot of work to do so.  I was fighting against the `setup` script which deletes existing builds, extracts, uses `&&` for mkdirs so the `cd`s won't work if the dir already exists, and other stuff like that.  Basically it just doesn't really facilitate rebuilding, or building with an already-cloned repo.

**Comment by Ptomerty** [comment]
I will pass this on, as I don't have control over the Ishiiruka repository.

Note that this is an installer that downloads a fresh copy of the repo and creates some convenient shortcuts; if you wanted, you could simply run

```bash
mkdir build && cd build
cmake .. -DLINUX_LOCAL_DEV=true
make
```
and be good to go with the compiled dolphin-emu, after extracting the config tarballs into the same directory.

EDIT: I have put in the idea to have Ishiiruka updated for 5.8.

**Comment by rawsp33d** [comment]
Yeah I ended up just running cmake and make myself, as if I were compiling dolphin directly. Okay cool, I wasn't aware how/if the projects were separated.  Thanks!

**Comment by Ptomerty** [comment]
As it appears 5.8 won't be coming out for a little bit, I'll manually patch
these changes in the script soon.

After you built, have you experienced desyncs with Windows users, or does
everything run as normal?

**Comment by rawsp33d** [comment]
Great question!  Everything works perfectly, with no desyncs.

**Comment by Ptomerty** [comment]
Added in https://github.com/Ptomerty/FasterMelee-installer/pull/33, closing unless you have further issues.

Thanks for notifying me!
