### ISSUE TITLE
Solus dependencies fix

### ISSUE THREAD

**Issue by Pizzabelly** [FasterMelee/FasterMelee-installer#36]
When trying to compile on Solus with the dependencies listed in the README there is an error while cmaking which is fixed by installing systemd-devel package with eopkg. Also for some reason you need to capitalize sfml-devel to SFML-devel for eopkg to pick it up. After those two the script works great on Solus 👍

**Comment by Ptomerty** [comment]
System.devel is the only package that works...

Do you know if you can use OR in eopkg? for example, `sudo eopkg it sfml-devel|SFML-devel`.

if you could try that and back to me, i can update the README. Thanks!

**Comment by Ptomerty** [comment]
Checked with official IRC. `system.devel` and `SFML-devel` are the updated packages. Updated in https://github.com/FasterMelee/FasterMelee-installer/commit/bf05a29caa9385dad2e61a316d92677dc0ff7bc8.
