### ISSUE TITLE
Makefile:160: recipe for target "all" failed

### ISSUE THREAD

**Issue by ruthslambat** [FasterMelee/FasterMelee-installer#41]
[ 66%] Building CXX object Externals/wxWidgets3/CMakeFiles/wx.dir/src/unix/utilsx11.cpp.o
[ 66%] Linking CXX static library libwx.a
[ 66%] Built target wx
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Ptomerty** [comment]
Make sure you have all dependencies installed.

When the installer asks you how many "cores" you want to use, enter `1`.

**Comment by ruthslambat** [comment]
That did it!
