### ISSUE TITLE
Outdated config

### ISSUE THREAD

**Issue by CodingKoopa** [FasterMelee/FasterMelee-installer#42]
With FasterMelee version [5.9b](https://github.com/FasterMelee/Ishiiruka/releases/tag/v5.9b), the most recent [config](https://github.com/FasterMelee/FasterMelee-installer/tree/master/config) is outdated. In my testing, the current 5.8.7 configuration seems to work fine with 5.9, but Linux packages rely on it being available at `/config/<version>-fmconfig.tar.gz`.

**Comment by Ptomerty** [comment]
If you are a supporter and have early access, please tag me or another mod
in the insider channel. Otherwise, please wait until the full beta release.
