### ISSUE TITLE
Installer Script Fails: Undefined Reference

### ISSUE THREAD

**Issue by muuud** [FasterMelee/FasterMelee-installer#44]
On Ubuntu 16.04 LTS, I installed all of the dependencies, and when I run the installer script, it fails at 

```
[ 95%] Building CXX object Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/WxEventUtils.cpp.o
[ 95%] Building CXX object Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/WXInputBase.cpp.o
[ 95%] Building CXX object Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/WxUtils.cpp.o
[ 95%] Building CXX object Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/X11Utils.cpp.o
[ 95%] Linking CXX executable ../../../Binaries/dolphin-emu
/usr/bin/ld: ../VideoCommon/libvideocommon.a(ImageWrite.cpp.o): undefined reference to symbol 'png_set_longjmp_fn@@PNG16_0'
/home/alex/anaconda2/lib/libpng16.so.16: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/build.make:2174: recipe for target 'Binaries/dolphin-emu' failed
make[2]: *** [Binaries/dolphin-emu] Error 1
CMakeFiles/Makefile2:1044: recipe for target 'Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/all' failed
make[1]: *** [Source/Core/DolphinWX/CMakeFiles/dolphin-emu.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

I have tried changing cpu cores from 16 to 1, as per the guidance here: https://github.com/FasterMelee/FasterMelee-installer/issues/41, but that only made it take longer to fail. I tried the solution suggested here: https://stackoverflow.com/questions/43144706/building-of-dolphin-emulator-on-ubuntu-16-10-fails-at-opengl-linking, but that appears to be a different issue. If it is worth noting, I have an old version of dolphin-emu installed from the repositories that works fine, I dont know if that is a problem. Also, I had some trouble with the NVIDIA drivers, and had to reinstall them, so might it be a problem with the PATH? Not sure if https://github.com/stevengj/libctl/issues/1 would be helpful, as I am simply running the script provided. Looking for any guidance.

**Comment by Ptomerty** [comment]
Are you sure that you have `libpng-dev` installed?

With some googling, it seems that your libpng is broken:
https://stackoverflow.com/questions/25965940/guacamole-libpng-undefined-reference-to-png-set-longjmp-fn
https://github.com/davisking/dlib/issues/220
https://stackoverflow.com/questions/21545076/libpng-png-set-longjmp-fn-not-found

See if you have it installed, and try `sudo apt-get install --reinstall libpng-dev` if it is.

**Comment by muuud** [comment]
Yes I believe I ran into those articles as well. I do have libpng-dev installed, but I tried the reinstall anyways, and it did not fix the issue, the script throws the same error. Could it be a problem with a symbolic link because of anaconda? I've seen that cause other strange errors before. Going to try taking it out of my path and trying the installation then.

**Comment by Ptomerty** [comment]
Hmm. Try running `sudo ldconfig -p | grep "libpng"` and i'll see if I can make sense of the output.
Source: https://github.com/fontforge/fontforge/issues/1537

Because that's not likely, you may just have to build from the External library by editing CMakeLists.txt: https://github.com/Tinob/Ishiiruka/blob/master/CMakeLists.txt#L606

Let's cross that bridge when we come to it, however.

**Comment by muuud** [comment]
Thanks for your concern and suggestions, however, simply removing anaconda from my PATH and running the installer again was successful, so I am closing this. Feel silly for posting it, but maybe someone else will encounter this same issue.
