### ISSUE TITLE
Compilation failing on archlinux

### ISSUE THREAD

**Issue by ccl2of4** [FasterMelee/FasterMelee-installer#50]
I am seeing an error while compiling on archlinux. It looks like it might be fixed if `-fexceptions` is passed to the compiler.

I'm not too familiar with cmake so I'm not quite sure how to fix this, but I'm hoping the solution is pretty straightforward.

A complete log from running the setup script is attached.

And thank you so much for maintaining this. I have been using this setup script for over a year to play netplay and I really appreciate the work you've put in to keep things working on linux :smile:

[log.txt](https://github.com/FasterMelee/FasterMelee-installer/files/2431889/log.txt)

**Comment by jangler** [comment]
I have the same problem, using version 2.1.0 of soundtouch. I couldn't figure out how to fix it in the cmake invocation in the setup script, so my workaround was to comment out line 62 of /usr/include/soundtouch/FIFOSamplePipe.h, compile, then uncomment it again.

**Comment by ghost** [comment]
Same build failure on Arch.

...
[ 57%] Building CXX object Externals/wxWidgets3/CMakeFiles/wx.dir/src/unix/stdpaths.cpp.o
[ 57%] Building CXX object Externals/wxWidgets3/CMakeFiles/wx.dir/src/unix/uiactionx11.cpp.o
[ 57%] Building CXX object Externals/wxWidgets3/CMakeFiles/wx.dir/src/unix/utilsx11.cpp.o
[ 57%] Linking CXX static library libwx.a
[ 57%] Built target wx
make: *** [Makefile:163: all] Error 2

**Comment by Ptomerty** [comment]
Hey guys! I've been really busy with school so I probably won't have time
to patch soundtouch, but I'll add the cmake flag to the installation script
later. Thanks for all the reports!

EDIT: The offending line appears in the master branch of Dolphin as well. For now, I suggest doing what jangler did up above.

**Comment by pavethem** [comment]
> I have the same problem, using version 2.1.0 of soundtouch. I couldn't figure out how to fix it in the cmake invocation in the setup script, so my workaround was to comment out line 62 of /usr/include/soundtouch/FIFOSamplePipe.h, compile, then uncomment it again.

What exactly is the line that should be commented out? Maybe the line number has changed, but commenting out line 62 does not solve this issue for me. Line 62 reads: "ST_THROW_RT_ERROR("Error: Illegal number of channels");"

**Comment by jangler** [comment]
Yup, that's the one.

**Comment by pavethem** [comment]
Nevermind, commenting out line 62 does fix the problem, I just didn't realize you had to comment using "///" and not "#" (It's C).
