### ISSUE TITLE
AUR package needs update

### ISSUE THREAD

**Issue by NickCondron** [FasterMelee/FasterMelee-installer#51]
The AUR repository linked in the README needs to be updated https://aur.archlinux.org/packages/dolphin-emu-faster-melee/

The last update to the package was in December 2017, but multiple new versions of FM have been released. If the AUR is no longer maintained, it should be removed from the README.

**Comment by Ptomerty** [comment]
Hello! I'm currently very busy, but I'll leave the link there for now;
the comments to say to use this installer if the AUR package is
outdated.

**Comment by Ptomerty** [comment]
Last update was in March 2019, making it reasonably maintained.
