### ISSUE TITLE
Fedora dependencies are incorrect

### ISSUE THREAD

**Issue by C-Higgins** [FasterMelee/FasterMelee-installer#55]
In Fedora, `gtk+-devel` should be `gtk2-devel` and `wxGTK-devel` should be `wxGTK3-devel` or `wxGTK31-devel` (see below).

Unfortunately, you are using wxGTK 3.1 which is a development release, not stable, and Fedora packages only up to the stable 3.0.4. So Fedora users will need to install 3.1 manually from [here.](https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries#toc3) This information should be added to the README

**Comment by Ptomerty** [comment]
Instead of changing it, I've updated it to use the recommended method on Dolphin's wiki, which is to install `dolphin-emu` first; see 4055e52
