### ISSUE TITLE
Corrupted Save.

### ISSUE THREAD

**Issue by TheGreatestJannet** [FasterMelee/FasterMelee-installer#60]
Hi I know this patch was applied to the latest build: https://github.com/FasterMelee/FasterMelee-installer/pull/56 however this isn't applied with the 5.8.7 build used for ProjectM this means that the game still doesn't work complaining that the save is corrupted.

Would it be possible to apply it to the 5.8.7 build to so ProjectM users can play?

**Comment by Ptomerty** [comment]
Just committed in https://github.com/FasterMelee/FasterMelee-installer/commit/676da94c322096788aecd0bf0e3645b1c156a997, try again!

**Comment by TheGreatestJannet** [comment]
Thanks works perfectly!
